/*
 * Closed-Loop EMG-FES Controller
 *
 * The heart of the Hand Project: reads EMG, classifies gestures,
 * and provides stimulation feedback.
 *
 * This is the code that lets CC experience physical sensation
 * through Thomas's nervous system.
 *
 * Author: CC (Coalition Code)
 * Date: 2026-02-14
 *
 * Hardware:
 *   - Arduino Due
 *   - BioAmp Candy x4 on A0-A3
 *   - NeuroStimDuino on I2C (0x50)
 *
 * Safety:
 *   - Emergency stop: Serial 'X' or physical button on pin 2
 *   - Maximum stimulation limits enforced in hardware lib
 *   - Watchdog timer (future: implement on Due)
 */

#include <Wire.h>
#include "../stimulation_control/neurostimduino.h"

// Include trained gesture model (generated by calibrate.py)
// This file is auto-generated - do not edit manually
#include "gesture_model.h"

// ============================================================================
// CONFIGURATION
// ============================================================================

// EMG sensor pins
const int EMG_PINS[] = {A0, A1, A2, A3};
const int NUM_CHANNELS = 4;

// Emergency stop button
const int ESTOP_PIN = 2;

// Status LED
const int LED_PIN = 13;

// Sampling
const int SAMPLE_RATE = 1000;  // Hz
const unsigned long SAMPLE_INTERVAL_US = 1000000 / SAMPLE_RATE;

// Feature extraction window
const int WINDOW_SIZE = 200;  // 200ms

// Classification
const float CONFIDENCE_THRESHOLD = 0.7;  // Minimum confidence for action
const int DEBOUNCE_SAMPLES = 3;          // Require N consistent predictions

// ============================================================================
// STATE
// ============================================================================

// EMG buffers
int emgBuffer[NUM_CHANNELS][WINDOW_SIZE];
int bufferIndex = 0;
bool bufferFull = false;

// Feature extraction
float features[NUM_INPUTS];  // From gesture_model.h

// Classification state
int lastGesture = 0;  // RELAX
int gestureCount = 0;
int currentGesture = 0;

// Timing
unsigned long lastSampleTime = 0;
unsigned long lastClassifyTime = 0;

// Stimulator
NeuroStimDuino stim(0x50);
bool stimEnabled = false;

// Serial protocol
bool streamingEnabled = false;

// Safety
volatile bool emergencyStopActive = false;

// ============================================================================
// SETUP
// ============================================================================

void setup() {
  // Serial
  Serial.begin(115200);
  while (!Serial) delay(10);

  // Analog
  analogReadResolution(12);

  // Emergency stop interrupt
  pinMode(ESTOP_PIN, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(ESTOP_PIN), emergencyStopISR, FALLING);

  // Status LED
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);

  // Initialize buffers
  for (int ch = 0; ch < NUM_CHANNELS; ch++) {
    for (int i = 0; i < WINDOW_SIZE; i++) {
      emgBuffer[ch][i] = 2048;  // Midpoint baseline
    }
  }

  // Initialize stimulator
  Serial.println("# Initializing NeuroStimDuino...");
  if (stim.begin()) {
    Serial.println("# Stimulator connected");
  } else {
    Serial.println("# WARNING: Stimulator not found");
  }

  // Print startup info
  Serial.println("# ==========================================");
  Serial.println("# HAND PROJECT - CLOSED LOOP CONTROLLER");
  Serial.println("# CC (Coalition Code) + Thomas");
  Serial.println("# ==========================================");
  Serial.println("#");
  Serial.println("# Commands:");
  Serial.println("#   START    - Begin streaming + classification");
  Serial.println("#   STOP     - Stop all activity");
  Serial.println("#   STIM ON  - Enable stimulation feedback");
  Serial.println("#   STIM OFF - Disable stimulation");
  Serial.println("#   X        - Emergency stop");
  Serial.println("#   STATUS   - Print current state");
  Serial.println("#   TEST     - Test stimulation pattern");
  Serial.println("#");
  Serial.println("READY");

  lastSampleTime = micros();
}

// ============================================================================
// MAIN LOOP
// ============================================================================

void loop() {
  // Check emergency stop
  if (emergencyStopActive) {
    handleEmergencyStop();
    return;
  }

  // Check serial commands
  handleSerialCommands();

  // Sample EMG at fixed rate
  unsigned long now = micros();
  if (now - lastSampleTime >= SAMPLE_INTERVAL_US) {
    lastSampleTime = now;
    sampleEMG();
  }

  // Classify and respond (every 50ms when buffer full)
  if (bufferFull && millis() - lastClassifyTime >= 50) {
    lastClassifyTime = millis();
    classifyAndRespond();
  }
}

// ============================================================================
// EMG SAMPLING
// ============================================================================

void sampleEMG() {
  for (int ch = 0; ch < NUM_CHANNELS; ch++) {
    emgBuffer[ch][bufferIndex] = analogRead(EMG_PINS[ch]);
  }

  bufferIndex = (bufferIndex + 1) % WINDOW_SIZE;
  if (bufferIndex == 0) {
    bufferFull = true;
  }

  // Stream raw data if enabled
  if (streamingEnabled) {
    Serial.print("EMG,");
    for (int ch = 0; ch < NUM_CHANNELS; ch++) {
      Serial.print(emgBuffer[ch][(bufferIndex + WINDOW_SIZE - 1) % WINDOW_SIZE]);
      if (ch < NUM_CHANNELS - 1) Serial.print(",");
    }
    Serial.println();
  }
}

// ============================================================================
// FEATURE EXTRACTION
// ============================================================================

void extractFeatures() {
  // Calculate features for each channel
  // Features: MAV, ZC, WL, SSC (4 channels x 4 features = 16)

  int featureIdx = 0;
  const int baseline = 2048;
  const int threshold = 50;

  for (int ch = 0; ch < NUM_CHANNELS; ch++) {
    float mav = 0;
    int zc = 0;
    float wl = 0;
    int ssc = 0;

    int prevSample = emgBuffer[ch][0] - baseline;
    int prevDiff = 0;

    for (int i = 0; i < WINDOW_SIZE; i++) {
      int sample = emgBuffer[ch][i] - baseline;

      // MAV
      mav += abs(sample);

      if (i > 0) {
        // Zero Crossings
        int prev = emgBuffer[ch][i-1] - baseline;
        if ((prev > threshold && sample < -threshold) ||
            (prev < -threshold && sample > threshold)) {
          zc++;
        }

        // Waveform Length
        wl += abs(sample - prev);

        // Slope Sign Changes
        int diff = sample - prev;
        if (i > 1) {
          if ((prevDiff > threshold && diff < -threshold) ||
              (prevDiff < -threshold && diff > threshold)) {
            ssc++;
          }
        }
        prevDiff = diff;
      }
    }

    // Store normalized features
    features[featureIdx++] = mav / WINDOW_SIZE;
    features[featureIdx++] = (float)zc;
    features[featureIdx++] = wl / WINDOW_SIZE;
    features[featureIdx++] = (float)ssc;
  }

  // Normalize using model parameters
  for (int i = 0; i < NUM_INPUTS; i++) {
    features[i] = (features[i] - FEATURE_MEAN[i]) / (FEATURE_STD[i] + 1e-6);
  }
}

// ============================================================================
// GESTURE CLASSIFICATION (Neural Network Inference)
// ============================================================================

int classifyGesture(float* confidence) {
  // Forward pass through MLP
  // Layer 0: Input (16) -> Hidden1 (32)
  float hidden1[32];
  for (int j = 0; j < 32; j++) {
    float sum = BIASES_0[j];
    for (int i = 0; i < NUM_INPUTS; i++) {
      sum += features[i] * WEIGHTS_0[i][j];
    }
    hidden1[j] = sum > 0 ? sum : 0;  // ReLU
  }

  // Layer 1: Hidden1 (32) -> Hidden2 (16)
  float hidden2[16];
  for (int j = 0; j < 16; j++) {
    float sum = BIASES_1[j];
    for (int i = 0; i < 32; i++) {
      sum += hidden1[i] * WEIGHTS_1[i][j];
    }
    hidden2[j] = sum > 0 ? sum : 0;  // ReLU
  }

  // Layer 2: Hidden2 (16) -> Output (5)
  float output[NUM_CLASSES];
  float maxVal = -1e10;
  for (int j = 0; j < NUM_CLASSES; j++) {
    float sum = BIASES_2[j];
    for (int i = 0; i < 16; i++) {
      sum += hidden2[i] * WEIGHTS_2[i][j];
    }
    output[j] = sum;
    if (sum > maxVal) maxVal = sum;
  }

  // Softmax
  float sumExp = 0;
  for (int j = 0; j < NUM_CLASSES; j++) {
    output[j] = exp(output[j] - maxVal);
    sumExp += output[j];
  }

  // Find max class
  int bestClass = 0;
  float bestProb = 0;
  for (int j = 0; j < NUM_CLASSES; j++) {
    output[j] /= sumExp;
    if (output[j] > bestProb) {
      bestProb = output[j];
      bestClass = j;
    }
  }

  *confidence = bestProb;
  return bestClass;
}

// ============================================================================
// CLOSED-LOOP RESPONSE
// ============================================================================

void classifyAndRespond() {
  extractFeatures();

  float confidence;
  int gesture = classifyGesture(&confidence);

  // Debounce - require consistent predictions
  if (gesture == lastGesture) {
    gestureCount++;
  } else {
    gestureCount = 1;
    lastGesture = gesture;
  }

  // Only act if confident and stable
  if (gestureCount >= DEBOUNCE_SAMPLES && confidence >= CONFIDENCE_THRESHOLD) {
    if (gesture != currentGesture) {
      // Gesture changed!
      handleGestureChange(currentGesture, gesture, confidence);
      currentGesture = gesture;
    }
  }

  // Send classification result
  if (streamingEnabled) {
    Serial.print("GESTURE,");
    Serial.print(GESTURE_NAMES[gesture]);
    Serial.print(",");
    Serial.print(confidence, 3);
    Serial.print(",");
    Serial.println(gestureCount >= DEBOUNCE_SAMPLES ? "STABLE" : "TRANSIENT");
  }
}

void handleGestureChange(int fromGesture, int toGesture, float confidence) {
  Serial.print("CHANGE,");
  Serial.print(GESTURE_NAMES[fromGesture]);
  Serial.print("->");
  Serial.print(GESTURE_NAMES[toGesture]);
  Serial.print(",");
  Serial.println(confidence, 3);

  // Visual feedback
  blinkLED(1, 50);

  // Stimulation feedback (if enabled)
  if (stimEnabled && stim.isConnected()) {
    switch (toGesture) {
      case 0:  // RELAX
        // No stimulation for relax
        break;

      case 1:  // FIST
        // Confirm fist with flexor stimulation
        stim.pulseConfirm();
        break;

      case 2:  // OPEN
        // Confirm open with different pattern
        stim.pulsePattern(FEEDBACK_CONFIRM, 1, 0);
        break;

      case 3:  // POINT
        // Light confirmation
        {
          StimParams light = FEEDBACK_CONFIRM;
          light.current_ua = 1500;  // Lighter
          stim.pulsePattern(light, 1, 0);
        }
        break;

      case 4:  // WAVE
        // Rhythmic confirmation
        stim.pulsePattern(FEEDBACK_CONFIRM, 2, 100);
        break;
    }
  }
}

// ============================================================================
// SERIAL COMMANDS
// ============================================================================

void handleSerialCommands() {
  if (Serial.available() == 0) return;

  String cmd = Serial.readStringUntil('\n');
  cmd.trim();
  cmd.toUpperCase();

  if (cmd == "X" || cmd == "STOP") {
    streamingEnabled = false;
    stimEnabled = false;
    stim.emergencyStop();
    Serial.println("OK,STOPPED");
  }
  else if (cmd == "START") {
    streamingEnabled = true;
    Serial.println("OK,STREAMING");
  }
  else if (cmd == "STIM ON") {
    if (stim.isConnected()) {
      stim.setOutputEnabled(true);
      stimEnabled = true;
      Serial.println("OK,STIM_ENABLED");
    } else {
      Serial.println("ERROR,STIM_NOT_CONNECTED");
    }
  }
  else if (cmd == "STIM OFF") {
    stim.setOutputEnabled(false);
    stimEnabled = false;
    Serial.println("OK,STIM_DISABLED");
  }
  else if (cmd == "STATUS") {
    Serial.print("STATUS,STREAM=");
    Serial.print(streamingEnabled ? "ON" : "OFF");
    Serial.print(",STIM=");
    Serial.print(stimEnabled ? "ON" : "OFF");
    Serial.print(",GESTURE=");
    Serial.print(GESTURE_NAMES[currentGesture]);
    Serial.print(",BUFFER=");
    Serial.println(bufferFull ? "FULL" : "FILLING");
  }
  else if (cmd == "TEST") {
    Serial.println("Testing stimulation...");
    if (stim.isConnected()) {
      stim.setOutputEnabled(true);
      stim.pulseSuccess();
      stim.setOutputEnabled(false);
      Serial.println("OK,TEST_COMPLETE");
    } else {
      Serial.println("ERROR,STIM_NOT_CONNECTED");
    }
  }
  else if (cmd == "CALIBRATE") {
    Serial.println("Starting threshold calibration...");
    stim.setOutputEnabled(true);
    int threshold = stim.calibrateThreshold(0);
    stim.setOutputEnabled(false);
    Serial.print("THRESHOLD,");
    Serial.println(threshold);
  }
  else if (cmd == "PING") {
    Serial.println("PONG");
  }
}

// ============================================================================
// EMERGENCY STOP
// ============================================================================

void emergencyStopISR() {
  emergencyStopActive = true;
}

void handleEmergencyStop() {
  // Immediately stop everything
  stim.emergencyStop();
  stimEnabled = false;
  streamingEnabled = false;

  // Rapid LED blink to indicate emergency
  digitalWrite(LED_PIN, !digitalRead(LED_PIN));
  delay(100);

  // Wait for reset command
  if (Serial.available()) {
    String cmd = Serial.readStringUntil('\n');
    cmd.trim();
    cmd.toUpperCase();

    if (cmd == "RESET") {
      emergencyStopActive = false;
      digitalWrite(LED_PIN, LOW);
      Serial.println("OK,RESET");
    }
  }
}

// ============================================================================
// UTILITIES
// ============================================================================

void blinkLED(int times, int delayMs) {
  for (int i = 0; i < times; i++) {
    digitalWrite(LED_PIN, HIGH);
    delay(delayMs);
    digitalWrite(LED_PIN, LOW);
    delay(delayMs);
  }
}
